export const productType = {
    FETCH_RECIPE_START: ' FETCH_RECIPE_START',
    FETCH_RECIPE_SUCCESS: ' FETCH_RECIPE_SUCCESS',
    FETCH_RECIPE_FAIL: 'FETCH_RECIPE_FAIL',
    GET_SEARCH_TEXT:'GET_SEARCH_TEXT',
    SET_SEARCH_TEXT_RESULT_REDUCER:'SET_SEARCH_TEXT_RESULT_REDUCER'
}

export const descriptionType = {
    GET_ITEM_PRODUCT_DESCRIPTION_PAGE: ' GET_ITEM_PRODUCT_DESCRIPTION_PAGE',
    GET_ITEM_ID_DESCRIPTION_FILTER: "GET_ITEM_ID_DESCRIPTION_FILTER",
    SET_ITEM_DESCRIPTION_REDUCER: 'SET_ITEM_DESCRIPTION_REDUCER',
}

export const CartType = {
    START_FETCH_CARD: 'START_FETCH_CARD',
    SET_CARD_REDUCER: "SET_CARD_REDUCER",
    ADD_PRODUCT_CART:"ADD_PRODUCT_CART"
}